@url=http://localhost:3000/api/event/

POST {{url}}create
Content-Type: application/json

{
  "title": "title",
  "description": "desc",
  "address": {
    "Street": "geistig Straße 123",
    "city": "cool city",
    "country": "austria",
    "state": "wien"
  },
  "location": {
    "latitude": "48.2082",
    "longitude": "16.3738"
  },
  "type": "event",
  "creator_id": "4608d979-d3e6-4b0b-bd36-783656a0f9ff",
  "status": "active",
  "chat": {
    "about": "chat about stuff",
    "name": "chat name"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "min age 18"
    },
    {
      "text": "max participants 50"
    },
    {
      "text": "no pets allowed"
    }
  ]
}

###

GET {{url}}/getAll

###

GET {{url}}/getLocationById/a3c008e2-04c5-4297-93a5-2e992310e5a5