@url=http://localhost:3000/api/event/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDEyQGdtYWlsLmNvbSJ9LCJleHAiOjE3MTcwOTQ3MDcuNzQ5LCJpYXQiOjE3MTcwOTI5MDd9.TCRWFwmfB7LgJSkryAUoy-IbiatLSiOV4vImWw0qTFk

POST {{url}}create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "title",
  "description": "desc",
  "address": {
    "Street": "geistig Straße 123",
    "city": "cool city",
    "country": "austria",
    "state": "wien"
  },
  "location": {
    "latitude": "48.2082",
    "longitude": "16.3738"
  },
  "type": "event",
  "status": "active",
  "chat": {
    "about": "chat about stuff",
    "name": "chat name"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "min age 18"
    },
    {
      "text": "max participants 50"
    },
    {
      "text": "no pets allowed"
    }
  ]
}
###

POST {{url}}create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Birthday Party",
  "description": "Come celebrate my birthday with me!",
  "address": {
    "Street": "123 Main Street",
    "city": "Springfield",
    "country": "United States",
    "state": "Illinois"
  },
  "location": {
    "latitude": "39.7817",
    "longitude": "-89.6501"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "Let's chat about the party details!",
    "name": "Birthday Bash Chat"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "Bring a gift!"
    },
    {
      "text": "RSVP by May 1st"
    },
    {
      "text": "No outside food allowed"
    }
  ]
}


###
POST {{url}}create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Music Festival",
  "description": "Join us for a weekend of music and fun!",
  "address": {
    "Street": "789 Festival Avenue",
    "city": "Groovetown",
    "country": "United States",
    "state": "California"
  },
  "location": {
    "latitude": "36.7783",
    "longitude": "-119.4179"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "Discuss lineup and ticket info here!",
    "name": "Festival Fever Chat"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "Bring sunscreen and water"
    },
    {
      "text": "No re-entry after 10pm"
    },
    {
      "text": "Pets on leashes allowed"
    }
  ]
}


###

POST {{url}}create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "title",
  "description": "desc",
  "address": {
    "Street": "geistig Straße 123",
    "city": "cool city",
    "country": "austria"
  },
  "location": {
    "latitude": "48.2082",
    "longitude": "16.3738"
  },
  "type": "event",
  "chat": "false",
  "price": 20.00,
  "max_participants": 1000,
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "requirements": [
    {
      "text": "min age 18"
    },
    {
      "text": "no smoking"
    },
    {
      "text": "no pets allowed"
    }
  ]
}

### register user to event

POST {{url}}register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "event_id": "a4ae88fd-b0e6-49af-a730-0da9c6334299"
}

### unregister user to event

POST {{url}}unregister
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "event_id": "1a153caf-b0a9-417f-b043-1b885633a25f"
}

### update event

POST {{url}}changeEventDetails
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "731b6d58-e980-4597-8c9f-be3e0f2c3ac7",
  "title": "Tech Conference 123123123",
  "description": "desc1231",
  "status": "active"
}

### delete event

DELETE {{url}}/deleteEvent
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "event_id": "8ccf736c-7367-4d68-9fae-c5df6317ba35"
}

###

GET {{url}}getAll

###

GET {{url}}getLocationById/a3c008e2-04c5-4297-93a5-2e992310e5a5

### get participants by event id

GET {{url}}getParticipantsFromEvent/a4ae88fd-b0e6-49af-a730-0da9c6334299
Authorization: Bearer {{token}}
