@url=http://localhost:3000/api/event/

POST {{url}}create
Content-Type: application/json

{
  "title": "title",
  "description": "desc",
  "address": {
    "Street": "geistig Straße 123",
    "city": "cool city",
    "country": "austria",
    "state": "wien"
  },
  "location": {
    "latitude": "48.2082",
    "longitude": "16.3738"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "chat about stuff",
    "name": "chat name"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "min age 18"
    },
    {
      "text": "max participants 50"
    },
    {
      "text": "no pets allowed"
    }
  ]
}
###

POST {{url}}create
Content-Type: application/json

{
  "title": "Birthday Party",
  "description": "Come celebrate my birthday with me!",
  "address": {
    "Street": "123 Main Street",
    "city": "Springfield",
    "country": "United States",
    "state": "Illinois"
  },
  "location": {
    "latitude": "39.7817",
    "longitude": "-89.6501"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "Let's chat about the party details!",
    "name": "Birthday Bash Chat"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "Bring a gift!"
    },
    {
      "text": "RSVP by May 1st"
    },
    {
      "text": "No outside food allowed"
    }
  ]
}


###
POST {{url}}create
Content-Type: application/json

{
  "title": "Music Festival",
  "description": "Join us for a weekend of music and fun!",
  "address": {
    "Street": "789 Festival Avenue",
    "city": "Groovetown",
    "country": "United States",
    "state": "California"
  },
  "location": {
    "latitude": "36.7783",
    "longitude": "-119.4179"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "Discuss lineup and ticket info here!",
    "name": "Festival Fever Chat"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "Bring sunscreen and water"
    },
    {
      "text": "No re-entry after 10pm"
    },
    {
      "text": "Pets on leashes allowed"
    }
  ]
}


###

POST {{url}}create
Content-Type: application/json

{
  "title": "Tech Conference",
  "description": "Stay updated with the latest in tech!",
  "address": {
    "Street": "456 Tech Boulevard",
    "city": "Silicon Valley",
    "country": "United States",
    "state": "California"
  },
  "location": {
    "latitude": "37.7749",
    "longitude": "-122.4194"
  },
  "type": "event",
  "creator_id": "053d7d34-9791-4c41-ada3-7a1bed48447a",
  "status": "active",
  "chat": {
    "about": "Exchange ideas and network here!",
    "name": "Tech Talk Chat"
  },
  "created_at": 1711833523765,
  "event_start_date": 1811833533765,
  "event_end_date": 1911834533765,
  "conditions": [
    {
      "text": "Open to all tech enthusiasts"
    },
    {
      "text": "No solicitation allowed"
    },
    {
      "text": "WiFi available"
    }
  ]
}


###

GET {{url}}/getAll

###

GET {{url}}/getLocationById/a3c008e2-04c5-4297-93a5-2e992310e5a5