@url=http://localhost:3000/api/user
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDEyQGdtYWlsLmNvbSJ9LCJleHAiOjE3MTM2Mzc1NzkuOTI5LCJpYXQiOjE3MTM2MzU3Nzl9.yWGoVwMQPmteGWTgWESLht30uMqabnwkZ2qlTm_48uM

POST {{url}}/signup
Content-Type: application/json

{
  "username": "testname",
  "email": "test12@gmail.com",
  "password": "123pw",
  "aboutme": "about me blabla"
}

### login

POST {{url}}/login
Content-Type: application/json

{
  "email": "test12@gmail.com",
  "password": "123pw"
}


### update username

PUT {{url}}/changeUsername/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "asdoijsaldjasl"
}

### delete user

DELETE {{url}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json
