@url=http://localhost:3000/api/user
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDEyQGdtYWlsLmNvbSJ9LCJleHAiOjE3MTYxNDI5MjAuMDA4LCJpYXQiOjE3MTYxNDExMjB9.Rqj2bdC2J0zCoEjoRb3FASRIvp0bnxtohhNBUcFQTrA

### signup

POST {{url}}/signup
Content-Type: application/json

{
  "username": "user",
  "email": "someone@gmail.com",
  "password": "1234",
  "about_me": "Ich bin ein Student"
}

### login

POST {{url}}/login
Content-Type: application/json

{
  "email": "admin@hotvite.com",
  "password": "admin"
}


### update username

PUT {{url}}/changeUsername/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "asdoijsaldjasl"
}

### delete user

DELETE {{url}}/delete
Authorization: Bearer {{token}}
Content-Type: application/json
